image: node:latest

cache:
  paths:
    - node_modules/

services:
  - mongo:latest

before_script:
  - npm install --silent

pages:
  script:
    - npm install -g jsdoc
    - npm install minami
    - jsdoc -c jsdoc.json -u tutorials
  artifacts:
    paths:
      - public

test_jnode:
  script:
    - node ./specs/test_jnode.js

test_api:
  script:
    - node ./specs/test_api.js

test_assets:
  script:
    - node ./specs/test_assets.js

test_view:
  script:
    - node ./specs/test_view.js

test_model:
  script:
    - node ./specs/test_model.js

test_logger:
  script:
    - node ./specs/test_logger.js

test_helper:
  script:
    - node ./specs/test_helper.js

test_validator:
  script:
    - node ./specs/test_validator.js

test_mongo:
  script:
    - node ./specs/test_mongo.js

test_promise:
  script:
    - node ./specs/test_promise.js

test_hash:
  script:
    - node ./specs/test_hash.js
