image: node:latest

before_script:
  - npm install --silent

pages:
  script:
    - npm install -g jsdoc
    - npm install minami
    - jsdoc -c jsdoc.json -u tutorials --readme readme.md
  artifacts:
    paths:
      - public
